---
- name: Provision VM in AWS with Terraform
  hosts: localhost

  roles:
    - role: terraform-vm-provisioning
      vars:
        infra_state: "{{ infra_state }}"
        force_init: "{{ force_init }}"
        server_count: "{{ server_count }}"
        prefix_instance_name: "{{ instance_name }}"
        instance_env: "{{ instance_env }}"
        project_name: "{{ project_name }}"
        git_user: '{{ lookup("env", "git_user") }}'
        git_token: '{{ lookup("env", "git_token") }}'
        git_repo_url: "https://{{ git_user }}:{{ git_token }}@github.com/froberge/ansible_terraform_config.git"
        git_work_dir: "/tmp/terraform/aws"
        pah_pass: '{{ lookup("env", "pah_pass") }}'
        git_name: "AAP service account"
        git_email: "cloudAutomation_aap@company.com"
