---
- name: ServiceNow Webhook trigger
  hosts: localhost

  sources:
    - ansible.eda.webhook:
        port: 5001

  rules:
    - name: Call ServiceNow Workflow
      condition: event.payload.description is defined
      action:
        run_workflow_template:
          name: AWS Terraform Demo
          organization: AAP TF SNow Demo
          extra_vars:
            ansible_eda: "{{ event.payload.message }}"
