---
- name: Configure firewalld to allow specific TCP ports on WebServers
  hosts: all
  become: true

  tasks:
    - name: Ensure firewalld is installed
      ansible.builtin.package:
        name: firewalld
        state: present

    - name: Ensure firewalld is running and enabled
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true

    - name: Allow TCP port 80
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true

    - name: Allow TCP port 8080
      ansible.posix.firewalld:
        port: 8080/tcp
        permanent: true
        state: enabled
        immediate: true

    - name: Allow TCP port 443
      ansible.posix.firewalld:
        service: https
        permanent: true
        state: enabled
        immediate: true

    - name: Reload firewalld service
      ansible.builtin.service:
        name: firewalld
        state: reloaded
