---
- name: Save Global Workflow Variables
  hosts: all

  tasks:
    - name: Set global workflow variables
      ansible.builtin.set_stats:
        data:
          project_name: "{{ project_name | lower | regex_replace('[^a-z0-9-]', '-') | trim('-') }}"
          itsm_request_id: "{{ request_id }}"
          # Group names derived from AWS instance tags based on project_name.
          lb_group_name: "tag_{{ project_name | lower | regex_replace('[^a-z0-9-]', '-') | trim('-') }}_lb"
          ws_group_name: "tag_{{ project_name | lower | regex_replace('[^a-z0-9-]', '-') | trim('-') }}_web"
