---
- name: Create the servicenow ticket information
  hosts: all

  tasks:
    - name: Set the request_id
      ansible.builtin.set_stats:
        data:
          itsm_request_id: "{{ request_id }}"

    - name: Set the loadbalancer url
      ansible.builtin.set_stats:
        data:
          response_url: "http://{{ ansible_host }}/info"
      when: "lb_group_name in group_names"

    - name: Set the hostnames
      ansible.builtin.set_stats:
        data:
          response_hostnames: "Hostname: {{ ansible_host }} \n"
      when: "ws_group_name in group_names"

    - name: Set the response_status
      ansible.builtin.set_stats:
        data:
          response_status: OK
        aggregate: false
